### ISSUE TITLE
This Channel is not responding error

### ISSUE THREAD

**Issue by Zenshu** [TehCrucible/KissAnime.bundle#1]
Running the latest PMS version on windows 10 64 bit platform and all I get when trying to access the channel is a screen that says "This channel is not responding."

![image](https://cloud.githubusercontent.com/assets/15631620/10909540/3bb2fa16-81f7-11e5-87aa-4bff60066114.png)

**Comment by TehCrucible** [comment]
Correct.  Unfortunately, I've abandoned this channel after the developers of the website took measures to block it.  It hasn't been updated in over two years.
